### ISSUE TITLE
Padding not being set if there is no padded 0

### ISSUE THREAD

**Issue by mathewpower** [4degrees/clique#10]
example

if we have an sequence like
test.1000.dpx
test.1001.dpx
test.1002.dpx etc

Then clique formats to

test.%d.dpx rather than test.%04.dpx

**Comment by martinpengellyphillips** [comment]
Closing this as wont fix. Clique can only see 1001-1030 as an unpadded sequence if there are no other frames present as otherwise 1-1000 would also be seen a 4 padded sequence which is incorrect. Perhaps report the issue to The Foundry to get their thoughts on why Nuke can't handle that path for you.

Note: If you want to force a sequence to 4 padded then just manually set the padding attribute on the collection instance:
```
collection.padding = 4
```
